### ISSUE TITLE
模块引入方式 是不是与原来的react-native-pili是一样的？

### ISSUE THREAD

**Issue by pj0579** [buhe/react-native-piliv2#2]
例如：Android

android/settings.gradle

include ':react-native-pili'
project(':react-native-pili').projectDir = new File(settingsDir, '../node_modules/react-native-pili/android')
android/app/build.gradle

dependencies {
    ...
    compile project(':react-native-pili')
}
还是这样设置吗？

**Comment by pj0579** [comment]
Android Streaming预览界面点击就卡住

**Comment by buhe** [comment]
安卓是一样的， iOS 改成了 cocoapods 引入降低开发成本。
